#help from https://www.youtube.com/watch?v=
server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/flashcard_db
    username: root
    password: admin123

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/